name: boostsecurity.io
run-name: ${{fromJSON(github.event.inputs.scan_params).run_name}}
on:
  workflow_dispatch:
    inputs:
       scan_params:
          description: The scan parameters
          required: true

jobs:
  boost-scanner:
    name: ${{fromJSON(github.event.inputs.scan_params).scanner_name}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{fromJSON(github.event.inputs.scan_params).repository}}
          token: ${{fromJSON(github.event.inputs.scan_params).token}}
          ref: ${{fromJSON(github.event.inputs.scan_params).branch_name}}
      - name: ${{fromJSON(github.event.inputs.scan_params).scanner_name}}
        uses: boostsecurityio/boostsec-scanner-github@v4
        with:
          api_token: ${{ secrets.BOOST_API_TOKEN }}
          registry_module: ${{fromJSON(github.event.inputs.scan_params).registry_module}}
        env:
          BOOST_GIT_HEAD: ${{fromJSON(github.event.inputs.scan_params).head_sha}}
          BOOST_GIT_BASE: ${{fromJSON(github.event.inputs.scan_params).base_sha}}
          BOOST_GIT_BRANCH: ${{fromJSON(github.event.inputs.scan_params).branch_name}}
          BOOST_GIT_MAIN_BRANCH: ${{fromJSON(github.event.inputs.scan_params).main_branch_name}}
          BOOST_GIT_PROJECT: ${{fromJSON(github.event.inputs.scan_params).repository}}
          BOOST_GIT_PULL_REQUEST: ${{fromJSON(github.event.inputs.scan_params).pull_request_id}}
